FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .
RUN go build -o /worker cmd/worker/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /worker /app/worker

CMD ["/app/worker"]
