FROM golang:1.22-alpine AS builder

WORKDIR /app

# Setup dependencies
COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .
RUN go build -o /api cmd/api/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /api /app/api

EXPOSE 8080
CMD ["/app/api"]
